### PR TITLE
FIX: Do not list interal (API) authorizations in user profile

### LINKED ISSUE #200: Hide Tomatoes authorizations
screenshot_20161103-082353

### PR DESCRIPTION
**Pull request by bugant**
TODO:

- [x] Add tests

Fix #200

### CODE REVIEW

File: app/models/authorization.rb [hunk 1]
```diff
@@ -39,6 +39,10 @@ def self.omniauth_image(auth)
     end
   end
 
+  def self.external_providers
+    return self.where('provider.ne': 'tomatoes')
```
Comment (potomak) [inline app/models/authorization.rb]: Things I'd do differently:

1. redundant `return`
1. redundant `self`

I like that you used the new hash syntax even with a string key!

Comment (potomak) [inline app/models/authorization.rb]: What would you think of a scope instead of a class method? The result would be very similar, but I like scopes because they're easier to spot when you search in the code. See https://docs.mongodb.com/ruby-driver/master/tutorials/5.1.0/mongoid-queries/#scoping.

Comment (bugant) [inline app/models/authorization.rb]: @potomak about return, I'm writing too much python these days :)

I've used a scope as you suggested.

**Comment by potomak** [comment]
@bugant feel free to merge it without testing the scope, I think it would be overkill.

**Comment by potomak** [comment]
@bugant we use auth provider names strings all over the code, do you think we should define some constants instead?

**Comment by potomak** [comment]
@bugant one last thing: we could use the same scope in the `Api::Presenter::User`, see https://github.com/tomatoes-app/tomatoes/blob/0.12.6/app/models/api/presenter/user.rb#L32.

**Comment by bugant** [comment]
@potomak yes I think it would be better to define provider names via constants... I'll have a look at it.

OK also for the presenter stuff.

File: app/models/authorization.rb [hunk 2]
```diff
@@ -12,7 +18,7 @@ class Authorization
 
   embedded_in :user
 
-  scope :external_providers, -> { where('provider.ne': 'tomatoes') }
+  scope :external_providers, -> { nin(provider: INTERNAL_PROVIDERS) }
```
Comment (potomak) [inline app/models/authorization.rb]: :1st_place_medal:

Comment (potomak) [inline app/models/authorization.rb]: Why not the opposite, that would also be the *non-negated* case? I mean why defining the external providers scope in terms of `INTERNAL_PROVIDERS`?

Comment (bugant) [inline app/models/authorization.rb]: @potomak make sense... :)
