### PR TITLE
Properly use user timezone in leaderboards

### LINKED ISSUE #258: Leaderboard score items expiration date timezone is wrong
Leaderboard score items don't expire according to users' timezones.

Example daily score item:

```javascript
{ _id: ObjectId("5897e27a814334000672964f"), uid: ObjectId("4e2d3ec0ad7f170001000001"), s: NumberLong("1"), eat: ISODate("2017-02-06T23:59:59.999Z") }
```

This is a my today's score item. The expiration date is set at tomorrow's end of day even if in my timezone, America/New York, is still 02/05.

The issue is that `IncrementScore#to_user_timezone` chances a UTC time's timezone instead of computing the correct local time according to user's timezone.

### PR DESCRIPTION
**Pull request by bugant**
Properly use user timezone in leaderboards

Fix #258

### CODE REVIEW

File: app/operations/increment_score.rb [hunk 1]
```diff
@@ -36,7 +35,8 @@ def user
     @user ||= User.find(user_id)
   end
 
-  def to_user_timezone(t)
-    t.in_time_zone(user.time_zone)
+  def now_in_user_zone
+    zone = user.time_zone ? ActiveSupport::TimeZone[user.time_zone] : Time.zone
```
Comment (potomak) [inline app/operations/increment_score.rb]: I think you could simplify as `ActiveSupport::TimeZone[user.time_zone] || Time.zone`, this way we would also handle invalid time zones.

**Comment by potomak** [comment]
@bugant the test should include an assertion the score's expiration date for a user in 'America/New_York', or any other time zone that is different from UTC, is `ActiveSupport::TimeZone#utc_offset` seconds from the expected expiration date.

You could add three tests, one per leaderboard collection that includes an expiration date, or one generic test.
